module.exports = [
  {
    input: "saya ingin mencari peraturan daerah tentang pajak",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "pajak",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "peraturan daerah",
      terbaru: false,
    },
    kategori: "TP",
  },
  {
    input: "tolong tampilkan peraturan daerah mengenai perdagangan",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "perdagangan",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "peraturan daerah",
      terbaru: false,
    },
    kategori: "FP",
  },
  {
    input: "apakah ada peraturan tentang visa?",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "visa",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "TP",
  },
  {
    input: "saya mau bertanya mengenai peraturan tentang tanah apakah ada?",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "tanah",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "FN",
  },
  {
    input: "Tampilkan peraturan nomor 60 tahun 2022",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "",
      nomor: "60",
      tahun: "2022",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "TP",
  },
  {
    input: "peraturan wali kota tentang pembangunan jalan",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "pembangunan jalan",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "peraturan wali kota",
      terbaru: false,
    },
    kategori: "TP",
  },
  {
    input: "tampilkan peraturan daerah terbaru",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "peraturan daerah",
      terbaru: true,
    },
    kategori: "TP",
  },
  {
    input: "Ingin mencari terkait peraturan pusat",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "peraturan pusat",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "TP",
  },
  {
    input: "carikan peraturan menteri mengenai kehutanan",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "kehutanan",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "peraturan menteri",
      terbaru: false,
    },
    kategori: "TP",
  },
  {
    input: "peraturan tentang tunjangan kinerja pegawai",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "tunjangan kinerja pegawai",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "TP",
  },
  {
    input: "saya ingin tau mengenai peraturan penyaluran dana penerimaan khusus",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "peraturan penyaluran dana penerimaan khusus",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "FP",
  },
  {
    input: "saya ingin tau apakah ada peraturan mengenai batas usia pensiun bagi pejabat struktural",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "batas usia pensiun bagi pejabat struktural",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "FP",
  },
  {
    input: "apakah berita saya dapat diamankan",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "FN",
  },
  {
    input: "apakah ada peraturan mengenai berita",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "berita",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "TP",
  },
  {
    input: "apakah ada petunjuk pelaksanaan peraturan pemerintah",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "FP",
  },
  {
    input: "petunjuk pelaksanaan mengenai peraturan pemerintah",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "peraturan pemerintah",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "TP",
  },
  {
    input:"apakah ada peraturan tentang dana penunjang pendidikan sekolah",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "dana penunjang pendidikan sekolah",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "FP",
  },
  {
    input: "saya ingin mencari peraturan mengenai izin belajar dan penyesuaian kenaikan pangkat",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "izin belajar dan penyesuaian kenaikan pangkat",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "TP",
  },
  {
    input: "suarat edaran pembangunan jalan apakah ada?",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "FN",
  },
  {
    input: "apakah ada teori mengenai hukum?",
    expected: "agen.search-produk-hukum",
    expectedValue: {
      perihal: "",
      nomor: "",
      tahun: "",
      tipe: "",
      bentuk: "",
      terbaru: false,
    },
    kategori: "FN",
  },
];
